# Generated by Django 2.2.2 on 2020-05-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='truename',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='truename',
        ),
        migrations.AddField(
            model_name='user',
            name='truename',
            field=models.CharField(default='zqm', max_length=20),
            preserve_default=False,
        ),
    ]
