# Generated by Django 2.2.2 on 2020-05-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('begin_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('form_method', models.IntegerField(default=0)),
                ('pic', models.CharField(default='default.jpg', max_length=64)),
                ('visit', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=256)),
                ('participation', models.IntegerField(default=0)),
                ('team_size_1', models.IntegerField(default=0)),
                ('team_number_1', models.IntegerField(default=0)),
                ('team_size_2', models.IntegerField(default=0)),
                ('team_number_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.FloatField(default=0)),
                ('bonus', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
    ]
