# Generated by Django 2.2.2 on 2020-05-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200515_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='course',
            name='visit',
        ),
    ]
