# Generated by Django 2.2.2 on 2020-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='team_num',
            field=models.IntegerField(default=0),
        ),
    ]
