# Generated by Django 2.2.2 on 2020-05-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_team_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='form_method',
        ),
    ]
