# Generated by Django 2.2.2 on 2020-05-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_form_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='form_method',
            field=models.IntegerField(default=0),
        ),
    ]
