# Generated by Django 2.2.2 on 2020-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200512_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='team_num',
        ),
        migrations.AddField(
            model_name='course',
            name='team_number_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='team_number_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='team_size_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='team_size_2',
            field=models.IntegerField(default=0),
        ),
    ]
