# Generated by Django 2.2.2 on 2020-05-05 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_participation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_auto_20200430_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='team',
        ),
        migrations.AddField(
            model_name='leader',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='team.Leader'),
        ),
    ]
