# Generated by Django 2.2.2 on 2020-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200515_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avg_GPA',
            field=models.FloatField(default=0),
        ),
    ]
