# Generated by Django 2.2.2 on 2020-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_avg_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='isInGPA',
            field=models.BooleanField(default=False),
        ),
    ]
