# Generated by Django 2.2.2 on 2020-05-05 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200505_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Leader'),
        ),
    ]
