# Generated by Django 2.2.2 on 2020-05-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20200505_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
    ]
