# Generated by Django 2.2.2 on 2020-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20200505_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='member',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
