# Generated by Django 2.2.2 on 2020-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
