# Generated by Django 2.2.2 on 2020-05-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20200430_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.IntegerField(default=0)),
                ('leader', models.IntegerField(default=0)),
                ('mark', models.FloatField(default=0)),
            ],
        ),
    ]
