# Generated by Django 2.2.2 on 2020-05-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20200515_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionitem',
            name='isFinishAssess',
        ),
        migrations.AddField(
            model_name='submissioncontribution',
            name='isFinishAssess',
            field=models.BooleanField(default=False),
        ),
    ]
