# Generated by Django 2.2.2 on 2020-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20200515_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionitem',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
