# Generated by Django 2.2.2 on 2020-05-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_invitation'),
        ('submission', '0004_submissionitem_isfinishassess'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncontribution',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
            preserve_default=False,
        ),
    ]
