# Generated by Django 2.2.2 on 2020-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_submissionitem_isfinished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionitem',
            name='isFinished',
            field=models.IntegerField(default=0),
        ),
    ]
