# Generated by Django 2.2.2 on 2020-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20200519_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionitem',
            name='isFinished',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
