# Generated by Django 2.2.2 on 2020-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20200519_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionitem',
            name='isFinished',
            field=models.IntegerField(default=0),
        ),
    ]
