# Generated by Django 2.2.2 on 2020-05-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20200519_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionitem',
            old_name='isFinished',
            new_name='is_finished',
        ),
    ]
